### ISSUE TITLE
can provide a cmake config file?

### ISSUE THREAD

**Issue by snakehaihai** [andreacasalino/MT_RRT#1]
HI 
can you provide a cmake config file so that the proposed system can be used across multiple os?

Regards
Shenghai Yuan

**Comment by snakehaihai** [comment]
also can provide a link to your paper? currently it is no where to be found

**Comment by andreacasalino** [comment]
Hi! Th project is now a CMake project and the core library as well as the examples can be compiled in any system.

The original paper can be accessed here https://ieeexplore.ieee.org/document/8967578 but you can find also the reference inside the documentation of the library (contained in ./doc/MT-RRT)
